import SearchInput from '@/components/search-input';

export default function Home() {
  return (
    <main>
      <section className='mb-10 bg-secondary/50 py-10'>
        <div className='container'>
          <div className='flex flex-col gap-4'>
            <h1 className='text-4xl font-extrabold text-primary'>The Community Showcase</h1>
            <p className='text-lg text-muted-foreground'>
              Browse through a collection of imaginative and visually stunning images generated by AI
            </p>
          </div>
        </div>
      </section>

      <section className='container'>
        <div className='mb-10 flex flex-col gap-2'>
          <span>Search posts</span>
          <SearchInput />
        </div>

        <div className='xs:grid-cols-2 grid grid-cols-1 gap-3 sm:grid-cols-3 lg:grid-cols-4'>Grid</div>
      </section>
    </main>
  );
}
