import SearchInput from '@/components/search-input';

export default function Home() {
  return (
    <main className='mb-20'>
      <section className='bg-secondary/50 pb-24 pt-16'>
        <div className='container'>
          <div className='flex flex-col gap-4'>
            <h1 className='text-center text-4xl font-extrabold text-primary md:text-left md:text-6xl'>
              Stunning Images with AI
            </h1>
            <p className='text-center text-xl font-light text-muted-foreground md:text-left md:text-3xl'>
              Browse through a collection of imaginative and visually stunning images generated by AI
            </p>
          </div>
        </div>
      </section>

      <div className='container flex -translate-y-12 items-center justify-center'>
        <div className=' mb-10 flex h-24 w-full flex-col items-center justify-center gap-2 rounded-lg  bg-white px-5 shadow-xl md:w-[500px]'>
          <SearchInput />
        </div>
      </div>

      <section className='container'>
        <div className='xs:grid-cols-2 grid grid-cols-1 gap-3 sm:grid-cols-3 lg:grid-cols-4'>Grid</div>
      </section>
    </main>
  );
}
