import { getRandomPrompt } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import FormField from '@/components/form-field';
import GeneratePromptButton from '@/components/surprise-me-button';

const CreatePostPage = () => {
  return (
    <>
      <main className='mb-20'>
        <section className='mb-10 bg-secondary/50 py-10'>
          <div className='container flex flex-col gap-4'>
            <h1 className='text-4xl font-extrabold text-primary'>Create</h1>
            <p className='text-lg text-muted-foreground'>
              Create imaginative and visually stunning images generated by AI and share them with the
              community.
            </p>
          </div>
        </section>

        <section>
          <FormField />
        </section>
      </main>
    </>
  );
};

export default CreatePostPage;
